# Generated by Django 5.2 on 2025-04-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_userprofile_reading_goal_readinglist_readinglistitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
